import { fetchQuery } from './queryExecutor';

export async function getDadosMRP(codEmp) {
    const query = `
SELECT
  OP.NUOP,
  OP.DTENTREGA,
  OP1.CODPROD,
  sankhya.FC_GET_NOME_PRODUTO_FORMULA_CEN(OP1.CODPROD, OP.CODPARC, OP1.IDFOR) AS PRODUTO,
  OP1.QTDPRODUCAO AS QTDPREVPRODUTO,
  sankhya.FC_GET_OPCAO_CAMPO('AD_CONTOP', 'STATUS', OP.STATUS) AS STATUS,
  OP2A.CODMATPRIMA AS CODMATERIAPRIMA,
  PRO.DESCRPROD AS MATERIAPRIMA,
  GRU.DESCRGRUPOPROD AS GRUPOMP,
  sankhya.FC_GET_OPCAO_CAMPO('TGFPRO', 'USOPROD', PRO.USOPROD) AS TIPOMP,
  OP2A.QTDMISTURA AS QTDORCADA,
  EST.ESTOQUE,
  ITE.QTDNEG AS QTDPREVCOMPRA,
  ITE.AD_DTPREVISAOENTREGA,
  ITE.AD_DTCONFENTR,
  CAB.NUNOTA AS NUUNPEDCOMPRA,
  CAB.NUMNOTA AS NUMPEDCOMPRA,
  NUUNCOMPRA,
  NUMCOMPRA,
  DTENTRADACOMPRA,
  QTDCOMPRA
 FROM sankhya.AD_CONTOP OP
 INNER JOIN sankhya.AD_CONTOP1 OP1 ON OP1.NUOP = OP.NUOP
 INNER JOIN sankhya.AD_CONTOP2A OP2A ON OP2A.NUOP = OP.NUOP AND OP2A.CODPROD = OP1.CODPROD
 INNER JOIN sankhya.TGFPRO PRO ON PRO.CODPROD = OP2A.CODMATPRIMA
 INNER JOIN sankhya.TGFGRU GRU ON GRU.CODGRUPOPROD = PRO.CODGRUPOPROD
 LEFT JOIN sankhya.TGFEST EST ON EST.CODPROD = PRO.CODPROD AND EST.CODEMP = OP.CODEMP AND EST.CODPARC = 0 AND EST.CODLOCAL = 101001
 LEFT JOIN sankhya.TGFITE ITE ON ITE.CODPROD = OP2A.CODMATPRIMA AND ITE.AD_NUOP = OP.NUOP
 LEFT JOIN sankhya.TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA AND CAB.TIPMOV = 'O'
 OUTER APPLY (
  SELECT
    MAX(CABC.NUNOTA) AS NUUNCOMPRA,
    MAX(CABC.NUMNOTA) AS NUMCOMPRA,
    MAX(CABC.DTENTSAI) AS DTENTRADACOMPRA,
    SUM(ITEC.QTDNEG) AS QTDCOMPRA
   FROM sankhya.TGFVAR V
   LEFT JOIN sankhya.TGFITE ITEC ON ITEC.NUNOTA = V.NUNOTA AND ITEC.SEQUENCIA = V.SEQUENCIA
   LEFT JOIN sankhya.TGFCAB CABC ON CABC.NUNOTA = V.NUNOTA
   WHERE V.NUNOTAORIG = CAB.NUNOTA AND V.SEQUENCIAORIG = ITE.SEQUENCIA
    AND ITEC.CODPROD = ITE.CODPROD
) AS COMPRA
 WHERE OP.STATUS NOT IN('F', 'C', 'A') AND OP.TIPO NOT IN('CGDE', 'CGTRANS') AND OP.CODEMP = ${codEmp}
`;

    return fetchQuery(query);
}
